### ISSUE TITLE
Medium article for how to use this

### ISSUE THREAD

**Issue by quisido** [CharlesStover/react-multi-context#6]

**Comment by toklok** [comment]
this repo is educational and beneficial imo, thanks.

**Comment by dai-shi** [comment]
Not related to this issue, but I just found this repo and I'm happy to see it because I was doing somthing pretty similar.
https://github.com/dai-shi/react-context-global-state
I don't see much discussion about using multiple contexts and I've been wondering if it's the right apporach... Just sharing my thought. Thanks.

**Comment by quisido** [comment]
I don't think I will get around to writing this article, so I'm closing this issue. 🙂
